### ISSUE TITLE
Removed from your discord?

### ISSUE THREAD

**Issue by SephirothSG** [l0ckb0x/L0ckb0x#4]
Hey L0ck, I'm a VIP user in your discord, it appears I've been removed?

Not sure if I accidentally left or if I was kicked, I am unable to message you on discord as you have pm's disabled.

**Comment by CandyVision** [comment]
The server got closed atm by discord.

**Comment by SephirothSG** [comment]
Closed by discord? Any proof as to this?

**Comment by l0ckb0x** [comment]
I just got up seems to be disabled

**Comment by NasmodorN** [comment]
New discord?

**Comment by l0ckb0x** [comment]
Yes 

https://discord.gg/RYPDkn2

Sent from Mail for Windows 10
